apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: trifacta-cluster-foundation
  namespace: default
spec:
  chart:
    spec:
      valuesFiles:
        - charts/cluster-foundation/values.yaml
        - charts/trifacta/values.yaml        
        - values/gke_trifacta-development_eu-west3-a_dataprep-dev.yaml
