apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: trifacta
  namespace: flux-resources
spec:
  interval: 1m
  url: ssh://git@phab.trifacta.com/diffusion/GCCONF/google-cloud-configuration.git
  secretRef:
    name: ssh-credentials
  ref:
    branch: wip_gitops_work

