apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: infrastructure
  namespace: trifacta-flux-resources
spec:
  interval: 1m0s
  sourceRef:
    kind: GitRepository 
    name: trifacta-flux-resources
  path: ./infrastructure
  prune: true
  validation: client
