apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: services-scheduled-job-runs
  namespace: scheduled-job-runs
spec:
  interval: 1m0s
  dependsOn:
    - name: migrate-dbs
      namespace: default
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  prune: true
  validation: client
  path: ./services/dataprep-dev-eu
  patchesStrategicMerge:
  # TODO - can the first values file be specified in the
  # non-cluster specific release.yaml?
  - charts/trifacta/values.yaml
  - charts/trifacta/values-scheduled.yaml
  - values/gke_trifacta-development_eu-west3-a_dataprep-dev.yaml
  - charts/trifacta/values-scheduled-job-runs-override.yaml
