apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: services-scheduled-job-runs
  namespace: scheduled-job-runs
spec:
  interval: 1m0s
  dependsOn:
    - name: migrate-dbs
      namespace: default
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./services-scheduled-job-runs/dataprep-dev-eu
  prune: true
  validation: client
  path: ./services/dataprep-dev-eu
