apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: trifacta-objects
  namespace: default
spec:
  releaseName: trifacta-objects
  chart:
    spec:
      chart: charts/cluster-objects
      sourceRef:
        kind: GitRepository
        name: trifacta-config-repo
        namespace: default
  interval: 1m0s
  install:
    remediation:
      retries: 3
