apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: trifacta-cluster-foundation
  namespace: flux-resources
spec:
  releaseName: trifacta-cluster-foundation
  chart:
    spec:
      chart: charts/cluster-foundation
      sourceRef:
        kind: GitRepository
        name: trifacta-config-repo
        namespace: flux-resources
      valuesFiles:
        - charts/cluster-foundation/values.yaml
        - charts/trifacta/values.yaml
  interval: 1m0s
  install:
    remediation:
      retries: 3
