apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: init-dbs
  namespace: default
spec:
  chart:
    spec:
      valuesFiles:
        # TODO - can the first values file be specified in the
        # non-cluster specific release.yaml?
        - charts/init-dbs/values.yaml
        - charts/trifacta/values.yaml
        - values/gke_trifacta-development_eu-west3-a_dataprep-dev.yaml
